feat(vinnie): add shrimp to the list
Porthorian/overengineered-eats pull request #1
Opened 2023-08-02 18:34 UTC by Porthorian

## Purpose

We need to add shrimp to the list this is topic of much need.

2023-08-02 18:36 UTC, zamerendino requested changes

2023-08-02 18:36 UTC, zamerendino commented on vinnie.md
> +21. Pizza
this list is supposed to be a source of TRUTH. All I see here is lies and deceit. We have not poured out life savings into this project for you to immediately make a mockery out of it. Pathetic.

2023-08-02 18:37 UTC, zamerendino commented on vinnie.md
> +21. Pizza
Pizza at 21??? I will sue.

2023-08-02 18:40 UTC, aanthonyrizzo requested changes
I dont believe you

2023-08-02 18:44 UTC, aanthonyrizzo commented
Great commit message format

2023-08-02 18:46 UTC, zamerendino commented
move pizza up to 15 at least and we got a deal here

2023-08-03 01:06 UTC, ddymko commented
I have _NEVER_ seen you eat shrimp or even order shrimp. Now, don't say "we never got it" because there are plenty of places we order from where we can get shrimp.

2023-08-03 03:05 UTC, Porthorian commented on vinnie.md
> +21. Pizza
Listen @zamerendino this took weeks to do and decide on this ordering. If you don't like it I'll take it up to the CTO. You signed a binding agreement to do thorough code reviews and this has not been a value add. Why are we paying you all these pennies?

2023-08-03 03:06 UTC, Porthorian commented
> I have _NEVER_ seen you eat shrimp or even order shrimp. Now, don't say "we never got it" because there are plenty of places we order from where we can get shrimp.

@ddymko I never got it cause I don't trust it from any place I'd order takeout from haha

2023-08-03 22:35 UTC, zamerendino commented
I refuse to let shrimp sit above pizza on your list.

2023-08-05 03:09 UTC, merged

2023-08-05 03:09 UTC, Porthorian commented
@zamerendino had to merge this in urgent bug fix.